basePath: /
host: localhost:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a simple API template using GoLang and Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: G1 GoLang Fiber API Template
  version: "1.0"
paths: {}
swagger: "2.0"
